name: Hugo

on:
  push:
    branches:
      - main
  schedule:
    - cron: '47 * * * *'  # “At minute 47.”
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: false
          fetch-depth: 0

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.108.0'
          extended: false

      - name: Build Website
        run: hugo --minify
