
baseurl = "https://popey.com/blog/"
title = "popey.com/blog"
languageCode = "en-gb"
#theme = "ghostwriter"
theme = "anubis"
[Params]
    mainSections = ["post"]
    intro = true
    headline = "Alan Pope's blog"
    description = "A bit of personal space for writing"
    github = "https://github.com/popey/popey.com-blog"
    twitter = "https://twitter.com/popey"
    email = "alan@popey.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:year/:month/:filename/"

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 6

[[menu.main]]
    url = "/contact/"
    name = "Contact"
    weight = 7

[[menu.main]]
    url = "/index.xml"
    name = "RSS"
    weight = 8